CREATE DATABASE IF NOT EXISTS bakery OWNER jvg_25;
GRANT ALL PRIVILEGES ON DATABASE bakery TO jvg_25;

CREATE TABLE IF NOT EXISTS "public"."users"(
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL
);
