CREATE DATABASE IF NOT EXISTS bakery;

USE bakery;

CREATE TABLE IF NOT EXISTS user(
    id INT NOT NULL AUTOINCREMENT,
    name VARCHAR(30) NOT NULL DEFAULT '',
    lastname VARCHAR(30) NOT NULL DEFAULT '',
    PRIMARY KEY(id)
);
